### ISSUE TITLE
GC config problem

### ISSUE THREAD

**Issue by viper645** [PurityWasHere/Anomaly-Mod-Hosting#1]
So i made a GC config and when i use it in bruteforce it skips to the end of my wordlist and i used numeric for wordlist and in config.
I found out that when i use only numbers it works but my code is with letters, capitals and numbers. Can u add that so it not only works with numbers for numeric?

**Comment by ishaan452** [comment]
Try using MailPass or UserPass as a workaround and see if it works then.
