### ISSUE TITLE
Tesseract Error (liblept1753.dll)

### ISSUE THREAD

**Issue by Unkn9wn1** [PurityWasHere/Anomaly-Mod-Hosting#14]
hi,
Tesseract won't work
this files is there in ob anomaly but ob could not find it and use it
i get errors until i install "Visual C++ Redistributable for Visual Studio 2015"

**Comment by camat741** [comment]
You just need to download Visual C ++ for Visual Studio 2015 x86

**Comment by Unkn9wn1** [comment]
yes, i said that too
`i get errors until i install "Visual C++ Redistributable for Visual Studio 2015"`

i don't remember what was my question for :\
sorry for this stupid q
