### ISSUE TITLE
*Minor issue* Discord invite link invalid

### ISSUE THREAD

**Issue by Pabsb** [PurityWasHere/Anomaly-Mod-Hosting#18]
Discord invite link in the splash window is invalid.

**Comment by ChrisGSA** [comment]
Yeah it's private now

**Comment by Pabsb** [comment]
I would like an invite since I was a donator.

**Comment by PurityWasHere** [comment]
https://discordapp.com/invite/jb8TFAF

**Comment by 1tarko** [comment]
invalid invite :(

**Comment by 1tarko** [comment]
> https://discordapp.com/invite/jb8TFAF

Invalid invite :(
