### ISSUE TITLE
Runner bug

### ISSUE THREAD

**Issue by Webaba** [PurityWasHere/Anomaly-Mod-Hosting#8]
- [ ] Wordlists are not showing up  when i create a new runner and click on select lists. 

But i have a lot of lists  in the wordlist tab.  
Delete and reload the Wordlist doesn't change anything. Restart doesn't help either.

Also  it ignores the settings for the proxy checker.  Proxykey and Proxysite.

Windows 7 

![Clipboard02](https://user-images.githubusercontent.com/58381446/69933832-5c267a00-14d0-11ea-9eb7-5321523b449c.jpg)

![Clipboard03](https://user-images.githubusercontent.com/58381446/69934310-d60b3300-14d1-11ea-8ff0-3d5823c703ca.jpg)

**Comment by PurityWasHere** [comment]
Fixed in latest update, a binding got deleted
